/* Offline precache. Same-origin resources only. No remote calls. */
const CACHE = "lean-crew-94f91dfbbfbc";
const ASSETS = ["./", "./index.html", "./styles.css", "./core.js", "./exercises.js", "./plans.js", "./theory.js", "./app.js", "./manifest.webmanifest", "./assets/biceps-curl.svg", "./assets/calf-raise.svg", "./assets/chest-press.svg", "./assets/dead-bug.svg", "./assets/dumbbell-row.svg", "./assets/glute-bridge.svg", "./assets/goblet-squat.svg", "./assets/hero.svg", "./assets/icon-192.png", "./assets/icon-512.png", "./assets/icon-maskable-512.png", "./assets/lat-pulldown.svg", "./assets/lateral-raise.svg", "./assets/leg-curl.svg", "./assets/leg-press.svg", "./assets/plank.svg", "./assets/push-up.svg", "./assets/reverse-lunge.svg", "./assets/seated-row.svg", "./assets/shoulder-press.svg", "./assets/theory/alan-blond-thinking.png", "./assets/theory/alan-caffeine-photo.png", "./assets/theory/alan-caffeine.png", "./assets/theory/alan-control-variables.png", "./assets/theory/alan-fashion-list.png", "./assets/theory/alan-food-opinion.png", "./assets/theory/alan-lean-diet.png", "./assets/theory/alan-meal-reply.png", "./assets/theory/alan-room-meme.png", "./assets/theory/alan-thin-club.png", "./assets/theory/alan-ucla-vlog.png", "./assets/theory/alan-victory.png", "./assets/theory/muscle-meme.png", "./assets/theory/sun-theory-access.png", "./assets/theory/sun-theory-body.png", "./assets/theory/sun-theory-intro.png", "./assets/theory/sun-version-answer.png", "./assets/triceps-pushdown.svg"];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS))));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('lean-crew-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET'||new URL(event.request.url).origin!==self.location.origin)return;
  event.respondWith(caches.match(event.request).then(cached=>cached||fetch(event.request)));
});
